name: starbound

services:
  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    networks:
      - default

networks:
  default:
    driver: bridge
    name: local-network
