name: Vercel Production Deployment

on:
  push:
    branches:
      - main

jobs:
  release:
    environment: production
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout project code
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          fetch-tags: true
          persist-credentials: false

      - name: setup semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/changelog@6.0.3
            @semantic-release/commit-analyzer@13.0.0
            @semantic-release/release-notes-generator@14.0.1
            @semantic-release/github@11.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.STARBOUND_DEPLOY_TOKEN }}

  migrations:
    environment: production
    needs: [release]
    name: Running Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci --force

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
        run: npm run prisma:deploy

  deploy:
    environment: production
    name: Deployment
    needs: [release, migrations]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
